### ISSUE TITLE
Adicionar post meta às notícias

### ISSUE THREAD

**Issue by eduardozulian** [redelivre/flacso#91]
- [x] Fonte (e, se houver, URL)
- [x] Editoria / palavras-chave
- [ ] ~~Projetos relacionados~~ (não teremos essa relação aqui)

**Comment by jacsonp** [comment]
Editoria tem aparência de tags, por exemplo:
Notícias
Opinião
Internacionales
Prosa e Verso
Biblioteca Virtual
Mundo
America
Internacional
Poder
Brasil
Política
El Mundo
Cuadernos del Pensamento Critico Latinoamericano
Colunistas
Especiales
Sociedade
Movimentos
Crítica
Rio de Janeiro
Ciencia y Universidad
Opinión
Rio
Cotidiano
Revista
Arte y Entretenimento

**Comment by eduardozulian** [comment]
São muitos os posts com essa editoria / palavras-chave, @jacsonp?

**Comment by jacsonp** [comment]
Sim
